# Generated by Django 4.2.13 on 2024-08-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reply_parent_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent_reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.reply'),
        ),
    ]
